# Reparing values

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np #
na_toy_df = pd.DataFrame(data = [[1,3,4,5],[2 ,6, np.nan]])

# make plots look nicer and increase font size
sns.set_theme(font_scale=2)
arabica_data_url = 'https://raw.githubusercontent.com/jldbc/coffee-quality-database/master/data/arabica_data_cleaned.csv'

coffee_df = pd.read_csv(arabica_data_url,index_col=0)


rhodyprog4ds_gh_events_url = 'https://api.github.com/orgs/rhodyprog4ds/events'
course_gh_df = pd.read_json(rhodyprog4ds_gh_events_url)

In [2]:
coffee_df.columns

Index(['Species', 'Owner', 'Country.of.Origin', 'Farm.Name', 'Lot.Number',
       'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner', 'Harvest.Year',
       'Grading.Date', 'Owner.1', 'Variety', 'Processing.Method', 'Aroma',
       'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity',
       'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Total.Cup.Points',
       'Moisture', 'Category.One.Defects', 'Quakers', 'Color',
       'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [3]:
col_name_mapper = {col_name:col_name.lower().replace('.','_') for col_name in coffee_df.columns}

In [4]:
coffee_df.rename(columns=col_name_mapper).head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [5]:
coffee_df.head(1)

,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,Region,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [6]:
coffee_df_fixedcols = coffee_df.rename(columns=col_name_mapper)
coffee_df_fixedcols.head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [7]:
coffee_df_fixedcols['unit_of_measurement'].value_counts()

m     1129
ft     182
Name: unit_of_measurement, dtype: int64

In [8]:
coffee_df_fixedcols['unit_of_measurement'].replace({'m':'meters','ft':'feet'})

1       meters
2       meters
3       meters
4       meters
5       meters
         ...
1307    meters
1308    meters
1309    meters
1310      feet
1312    meters
Name: unit_of_measurement, Length: 1311, dtype: object

In [9]:
coffee_df_fixedcols['unit_of_measurement_long'] = coffee_df_fixedcols['unit_of_measurement'].replace(
                                    {'m':'meters','ft':'feet'})
coffee_df_fixedcols.head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters,unit_of_measurement_long
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,meters

In [10]:
coffee_df_fixedcols.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1311 entries, 1 to 1312
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   species                   1311 non-null   object
 1   owner                     1304 non-null   object
 2   country_of_origin         1310 non-null   object
 3   farm_name                 955 non-null    object
 4   lot_number                270 non-null    object
 5   mill                      1001 non-null   object
 6   ico_number                1165 non-null   object
 7   company                   1102 non-null   object
 8   altitude                  1088 non-null   object
 9   region                    1254 non-null   object
 10  producer                  1081 non-null   object
 11  number_of_bags            1311 non-null   int64
 12  bag_weight                1311 non-null   object
 13  in_country_partner        1311 non-null   object
 14  harvest_year              1264 non-null   object
 15  grading_date              1311 non-null   object
 16  owner_1                   1304 non-null   object
 17  variety                   1110 non-null   object
 18  processing_method         1159 non-null   object
 19  aroma                     1311 non-null   float64
 20  flavor                    1311 non-null   float64
 21  aftertaste                1311 non-null   float64
 22  acidity                   1311 non-null   float64
 23  body                      1311 non-null   float64
 24  balance                   1311 non-null   float64
 25  uniformity                1311 non-null   float64
 26  clean_cup                 1311 non-null   float64
 27  sweetness                 1311 non-null   float64
 28  cupper_points             1311 non-null   float64
 29  total_cup_points          1311 non-null   float64
 30  moisture                  1311 non-null   float64
 31  category_one_defects      1311 non-null   int64
 32  quakers                   1310 non-null   float64
 33  color                     1095 non-null   object
 34  category_two_defects      1311 non-null   int64
 35  expiration                1311 non-null   object
 36  certification_body        1311 non-null   object
 37  certification_address     1311 non-null   object
 38  certification_contact     1311 non-null   object
 39  unit_of_measurement       1311 non-null   object
 40  altitude_low_meters       1084 non-null   float64
 41  altitude_high_meters      1084 non-null   float64
 42  altitude_mean_meters      1084 non-null   float64
 43  unit_of_measurement_long  1311 non-null   object
dtypes: float64(16), int64(3), object(25)
memory usage: 460.9+ KB

In [11]:
coffee_df_fixedcols['lot_number'].dtype

dtype('O')

In [12]:
coffee_df_fixedcols['lot_number'].value_counts()

1                             18
020/17                         6
019/17                         5
2                              3
102                            3
                              ..
11/23/0696                     1
3-59-2318                      1
8885                           1
5055                           1
017-053-0211/ 017-053-0212     1
Name: lot_number, Length: 221, dtype: int64

In [13]:
coffee_df_fixedcols['lot_number'].fillna('1')

1                                1
2                                1
3                                1
4                                1
5                                1
                   ...
1307                             1
1308                             1
1309    017-053-0211/ 017-053-0212
1310                             1
1312                           103
Name: lot_number, Length: 1311, dtype: object

In [14]:
coffee_df_fixedcols['lot_number_clean'] = coffee_df_fixedcols['lot_number'].fillna('1')

In [15]:
coffee_df_fixedcols['lot_number_clean'].value_counts()

1                             1059
020/17                           6
019/17                           5
102                              3
103                              3
                              ...
3-59-2318                        1
8885                             1
5055                             1
MCCFWXA15/16                     1
017-053-0211/ 017-053-0212       1
Name: lot_number_clean, Length: 221, dtype: int64

In [16]:
coffee_df_fixedcols.shape

(1311, 45)

In [17]:
coffee_df_fixedcols.dropna().shape

(130, 45)

In [18]:
coffee_df_fixedcols.head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters,unit_of_measurement_long,lot_number_clean
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,meters,1

In [19]:
coffee_df_fixedcols.dropna(subset=['altitude_low_meters']).shape

(1084, 45)

In [20]:
coffee_alt_df = coffee_df_fixedcols.dropna(subset=['altitude_low_meters'])

In [21]:
n_rows, n_cols = coffee_df_fixedcols.shape
coffee_df_fixedcols.dropna(thresh = .7*n_rows, axis=1).shape

(1311, 44)

In [22]:
coffee_df_fixedcols.dropna(thresh = .85*n_rows, axis=1).shape

(1311, 34)

In [23]:
coffee_df_fixedcols['in_country_partner'].value_counts().sort_index()

AMECAFE                                                                                  205
Africa Fine Coffee Association                                                            49
Almacafé                                                                                 178
Asociacion Nacional Del Café                                                             155
Asociación Mexicana De Cafés y Cafeterías De Especialidad A.C.                             6
Asociación de Cafés Especiales de Nicaragua                                                8
Blossom Valley International                                                              58
Blossom Valley International\n                                                             1
Brazil Specialty Coffee Association                                                       67
Central De Organizaciones Productoras De Café y Cacao Del Perú - Central Café & Cacao      1
Centro Agroecológico del Café A.C.                                                         8
Coffee Quality Institute                                                                   7
Ethiopia Commodity Exchange                                                               18
Instituto Hondureño del Café                                                              60
Kenya Coffee Traders Association                                                          22
METAD Agricultural Development plc                                                        15
NUCOFFEE                                                                                  36
Salvadoran Coffee Council                                                                 11
Specialty Coffee Ass                                                                       1
Specialty Coffee Association                                                             295
Specialty Coffee Association of Costa Rica                                                42
Specialty Coffee Association of Indonesia                                                 10
Specialty Coffee Institute of Asia                                                        16
Tanzanian Coffee Board                                                                     6
Torch Coffee Lab Yunnan                                                                    2
Uganda Coffee Development Authority                                                       22
Yunnan Coffee Exchange                                                                    12
Name: in_country_partner, dtype: int64

In [24]:
partner_corrections = {'Blossom Valley International\n':'Blossom Valley International',
  'Specialty Coffee Ass':'Specialty Coffee Association'}

In [25]:
coffee_df_clean = coffee_df_fixedcols.replace(partner_corrections)

## unpacking jsons

In [26]:
rhodyprog4ds_gh_events_url

'https://api.github.com/orgs/rhodyprog4ds/events'

In [27]:
gh_df = pd.read_json(rhodyprog4ds_gh_events_url)

In [28]:
type(gh_df.loc[0])

pandas.core.series.Series

In [29]:
a= '1'

In [30]:
type(a)

str

In [31]:
type(int(a))

int

In [32]:
pd.Series(gh_df.loc[0]['actor'])

id                                                        10656079
login                                                  brownsarahm
display_login                                          brownsarahm
gravatar_id
url                       https://api.github.com/users/brownsarahm
avatar_url       https://avatars.githubusercontent.com/u/10656079?
dtype: object

In [33]:
gh_df['actor'].apply(pd.Series).head()

,id,login,display_login,gravatar_id,url,avatar_url
0,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
1,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
2,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
3,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
4,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?

In [34]:
gh_df.head(1)

,id,type,actor,repo,payload,public,created_at,org
0,27175717296,DeleteEvent,"{'id': 10656079, 'login': 'brownsarahm', 'disp...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'ref': 'link', 'ref_type': 'branch', 'pusher_...",True,2023-02-18 01:24:55+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."

In [35]:
js_cols = ['actor','repo','payload','org']

In [36]:
pd.concat([gh_df[col].apply(pd.Series).rename(lambda c: '_'.join([c,col])) for col in js_cols],axis=1).head()

TypeError: sequence item 0: expected str instance, int found

In [37]:
gh_df['actor'].apply(pd.Series).rename(columns=lambda c: '_'.join([c,'actor']))

,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor
0,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
1,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
2,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
3,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
4,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
5,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
6,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
7,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
8,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
9,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
10,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
11,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
12,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
13,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
14,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
15,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
16,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
17,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
18,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
19,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
20,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
21,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
22,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
23,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
24,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
25,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
26,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
27,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
28,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
29,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?

In [38]:
json_cols_df = pd.concat([gh_df[col].apply(pd.Series).rename(columns=lambda c: '_'.join([c,col])) for col in js_cols],axis=1).head()

In [39]:
gh_df.columns

Index(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at',
       'org'],
      dtype='object')

In [40]:
json_cols_df.columns

Index(['id_actor', 'login_actor', 'display_login_actor', 'gravatar_id_actor',
       'url_actor', 'avatar_url_actor', 'id_repo', 'name_repo', 'url_repo',
       'ref_payload', 'ref_type_payload', 'pusher_type_payload',
       'repository_id_payload', 'push_id_payload', 'size_payload',
       'distinct_size_payload', 'head_payload', 'before_payload',
       'commits_payload', 'action_payload', 'number_payload',
       'pull_request_payload', 'master_branch_payload', 'description_payload',
       'release_payload', 'id_org', 'login_org', 'gravatar_id_org', 'url_org',
       'avatar_url_org'],
      dtype='object')

In [41]:
pd.concat([gh_df[['id','type','public','created_at']],json_cols_df],)

,id,type,public,created_at,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor,...,number_payload,pull_request_payload,master_branch_payload,description_payload,release_payload,id_org,login_org,gravatar_id_org,url_org,avatar_url_org
0,2.717572e+10,DeleteEvent,True,2023-02-18 01:24:55+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.717572e+10,PushEvent,True,2023-02-18 01:24:54+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.717572e+10,PullRequestEvent,True,2023-02-18 01:24:54+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.717571e+10,PullRequestEvent,True,2023-02-18 01:24:32+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.717571e+10,CreateEvent,True,2023-02-18 01:24:11+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2.713725e+10,PushEvent,True,2023-02-16 14:05:14+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.713723e+10,ReleaseEvent,True,2023-02-16 14:04:14+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.713719e+10,CreateEvent,True,2023-02-16 14:03:04+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2.713718e+10,PushEvent,True,2023-02-16 14:02:34+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.709641e+10,ReleaseEvent,True,2023-02-15 03:30:12+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2.709639e+10,PushEvent,True,2023-02-15 03:28:21+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.709637e+10,CreateEvent,True,2023-02-15 03:26:55+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.709636e+10,PushEvent,True,2023-02-15 03:25:54+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.709519e+10,PushEvent,True,2023-02-15 01:49:53+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2.709516e+10,PushEvent,True,2023-02-15 01:47:36+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2.702796e+10,PushEvent,True,2023-02-11 21:06:45+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2.702795e+10,PushEvent,True,2023-02-11 21:04:44+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2.702606e+10,PushEvent,True,2023-02-11 16:14:54+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2.702605e+10,PushEvent,True,2023-02-11 16:14:32+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2.702604e+10,PushEvent,True,2023-02-11 16:12:46+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2.702599e+10,PushEvent,True,2023-02-11 16:05:31+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2.702598e+10,PushEvent,True,2023-02-11 16:03:22+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2.699789e+10,PushEvent,True,2023-02-10 03:50:55+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2.699787e+10,PushEvent,True,2023-02-10 03:48:46+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2.699644e+10,PushEvent,True,2023-02-10 01:42:31+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2.699641e+10,ReleaseEvent,True,2023-02-10 01:40:27+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2.699640e+10,PushEvent,True,2023-02-10 01:39:41+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2.699640e+10,CreateEvent,True,2023-02-10 01:39:34+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.699368e+10,PushEvent,True,2023-02-09 22:15:42+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2.699364e+10,PushEvent,True,2023-02-09 22:13:20+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
1,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
2,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,7.0,{'url': 'https://api.github.com/repos/rhodypro...,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
3,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,7.0,{'url': 'https://api.github.com/repos/rhodypro...,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
4,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,main,Releases below is course announcements,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?

In [42]:
gh_df_clean = pd.concat([gh_df[['id','type','public','created_at']],json_cols_df],axis=1)
gh_df_clean.head()

,id,type,public,created_at,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor,...,number_payload,pull_request_payload,master_branch_payload,description_payload,release_payload,id_org,login_org,gravatar_id_org,url_org,avatar_url_org
0,27175717296,DeleteEvent,True,2023-02-18 01:24:55+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
1,27175717207,PushEvent,True,2023-02-18 01:24:54+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
2,27175717138,PullRequestEvent,True,2023-02-18 01:24:54+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,7.0,{'url': 'https://api.github.com/repos/rhodypro...,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
3,27175714675,PullRequestEvent,True,2023-02-18 01:24:32+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,7.0,{'url': 'https://api.github.com/repos/rhodypro...,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
4,27175712282,CreateEvent,True,2023-02-18 01:24:11+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,main,Releases below is course announcements,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?